### ISSUE TITLE
Find attitude fails

### ISSUE THREAD

**Issue by javierggt** [sot/find_attitude#19]
Find-attitude fails in a test by PCAD, while SAUSAGE manages to find an attitude.

- snapshot: [EHS_A_ACA_ALL_2021270.000101.txt](https://icxc.cfa.harvard.edu/aspect/test_review_outputs/web-kadi/find-attitude-07-2022/2021270_NPM/EHS_A_ACA_ALL_2021270.000101.txt)
- starcat: [starcat_2021270.000101.txt](https://icxc.cfa.harvard.edu/aspect/test_review_outputs/web-kadi/find-attitude-07-2022/2021270_NPM/starcat_2021270.000101.txt)
- current flight: [FA_snap_1_2021270.000101.png](https://icxc.cfa.harvard.edu/aspect/test_review_outputs/web-kadi/find-attitude-07-2022/2021270_NPM/FA_snap_1_2021270.000101.png)
- sausage output, for reference: [SAUSAGE_2021270.000101.png](https://icxc.cfa.harvard.edu/aspect/test_review_outputs/web-kadi/find-attitude-07-2022/2021270_NPM/SAUSAGE_2021270.000101.png)

**Comment by taldcroft** [comment]
It looks like the problem is in the web front end (both current production and the new version). Somehow the tolerance parameter is not being set to the user-supplied value. When I do this case "by hand" with a tolerance of 3.0 arcsec it finds an attitude solution:
```
In [1]: txt = """slot yag zag mag
   ...: 0     -768.95   -1747.60      7.0
   ...: 1     2145.03     162.55      7.1
   ...: 2    -1822.70     156.53      7.1
   ...: 3      797.70   -2078.80      7.1
   ...: 4     2078.75     -73.90      9.3
   ...: 5    -2050.45    -963.75      8.6
   ...: 6    -1922.23    -400.10      9.4
   ...: 7     -589.58    1532.65      6.7
   ...: """

In [2]: from find_attitude.find_attitude import *

In [4]: stars = get_stars_from_text(txt)

In [5]: solutions = find_attitude_solutions(stars, tolerance=3.0)
2022-07-26 18:29:37,977 Using AGASC pairs file /Users/aldcroft/ska/data/find_attitude/distances.h5
2022-07-26 18:29:37,986 Starting get_match_graph
2022-07-26 18:29:37,986 Getting matches from file
2022-07-26 18:29:39,307 Adding edges from 1105350 matching distance pairs
2022-07-26 18:29:48,407 Added total of 359426 nodes
2022-07-26 18:29:48,415 Getting all triangles from match graph
2022-07-26 18:29:50,677 Finding triangles that match stars pattern
2022-07-26 18:29:50,861 Checking clique [452728128, 452729840, 452731944, 452731232]
2022-07-26 18:29:50,861 
2022-07-26 18:29:50,865 Done with graph matching
Dataset               = 1
Method                = neldermead
Statistic             = chi2
Initial fit statistic = 1.98127e+07
Final fit statistic   = 5.50698 at function evaluation 259
Data points           = 8
Degrees of freedom    = 6
Probability [Q-value] = 0.480613
Reduced statistic     = 0.91783
Change in statistic   = 1.98127e+07
   yagzag.dra     -807.106    
   yagzag.ddec    2074.04     
Dataset               = 1
Method                = neldermead
Statistic             = chi2
Initial fit statistic = 5.50698
Final fit statistic   = 5.20658 at function evaluation 314
Data points           = 8
Degrees of freedom    = 5
Probability [Q-value] = 0.391193
Reduced statistic     = 1.04132
Change in statistic   = 0.300399
   yagzag.dra     -807.142    
   yagzag.ddec    2074.03     
   yagzag.droll   0.260508    
```

**Comment by javierggt** [comment]
Well, that's good, because it means I can fix it right away.

**Comment by taldcroft** [comment]
In https://github.com/sot/kadi-apps/blob/main/kadi_apps/blueprints/find_attitude/templates/find_attitude/index.html:

```
<form action="/find_attitude/" method="post">

  <div class="row">
    <div class="col">
      <label for="distance_tolerance">Distance tolerance (arcsec) </label>
      <input type="text" class="form-control" id="distance_tolerance" name="tolerance" value="{{distance_tolerance}}"> 
    </div>
  </div>
```
I think that it should be `name="distance_tolerance"` since the `get` asks for that and not `tolerance`.

**Comment by javierggt** [comment]
FIxed already.

**Comment by taldcroft** [comment]
Nice. I tried testing on web-kadi-test and it still fails. Is the fixed deployed on kadi-test?

**Comment by javierggt** [comment]
It is not on kadi-test because I know it is going to work. I tested it in my local development setup.

**Comment by taldcroft** [comment]
We definitely want to get this in to test for the flight promotion and give Eric a chance to re-do his failing test and sign off that it is passing now. I'm really excited that we found and can easily fix a bug like this now.

**Comment by javierggt** [comment]
I thought of merging this, modify web-kadi env file, install in kadi-test (with the patch release), then tell Eric, and so on.

If I install now on kadi-test, then I have to install again after I make the patch release, but I KNOW it is going to work.

**Comment by javierggt** [comment]
I installed the fix in kadi-test

**Comment by taldcroft** [comment]
And I have seen with my own eyes now that it does work, thanks! :tada:
